name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1b40af4435d5517ea2f44699db3f4647f79ef67c701d04e12790f07881b174f"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
