name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30d93fc31bc830d05db823670ee9f2686744491b261caeab453aba12c8d2b925"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
