name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cda198d859f3a537d477d843571fdcde4f1a4f0bbd67f99e8b91e99ca2a1a8d2"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
