name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe08cda7763998fbf579d45e7681b2c914783ad6a2f5c03624107db1912e1422"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
