name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85fbab091cd3a49c7698b12ff0e238fce79dfbb1181a4e9c8356f9e0c892990f"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
