name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84d1c745492a6ad0087acabe14ad9a4cafd5b9260478a9710cc7f36842563cc"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
