name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e192c39dd24a2f08adb1d51b1c44620dcf157ab8231406551b9140e5803fde97"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
