name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41f20474cae3984b00e73f28a8c87cc133bce4e73de006034bbe84646a18c462"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
