name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d3d21e7501d3a8914e7d05140cdd490765d7ecc927f4165bea33c8544391583"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
