name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ead2ac13b3b81270357ac8d0d80ec6b4490e29a03ee9b800ecc54b6f34f3a8f4"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
