name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a05516bcb73a3bad8b39ca5210af857ddf70966859fb1750b2b0dc0fed5758bb"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
