name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11d69c31821969cdc2edaad5189e4b8ae6ec91939fd69733076c1e4151fe77e6"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
