name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fd9795961072b84d4c39eb05f8e8515ab281de94c123a57050e5bc53381366f"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
