name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a218104737665666e2a4e41c35ff4f3cc719f514b3fbbbd2a8caab871950227"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
