name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31921ffb378f6f5bba988bda8b16d63977cd084c4064a9211afbb40b435c494c"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
