name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cefa98d1086a58446564738d6a0105c6c5fc091c44bd129d7c8b662ea385e36"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
