name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1511b5c610622e08e9b7b2c445af86c4874fa5ecf74c3a78052a6a088919089"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
