name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "896fdc587540cfee46ae7a0b83cc4a5216ec3642415bc3b042f93c015c13bc21"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
