name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02cda25084ad3e7ec40fd044031cf9147eab7ee0374858f6f83c058b52fc3cf5"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
