name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14bf72318fc2fae7e3767e22de4ba2fe3afa3fea6d164f0b2044def476783694"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
