name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff586a00919eac6d0899442e08df367de3d86350f4fea974e784698ef9f7855"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
