name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84e00273967b0863343d2ff2d033bd89055a89f8ac31e44ba825435b861ba62"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
