name = "Creation"
author = "Ozoku & oZo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8c45d6873a1ec178925a6913658197d1ed0253160b9a7aa4b19a137ce35e1b"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
